apiVersion: v1
kind: Service
metadata:
  name: pokemon
  labels:
    app: pokemon
spec:
  type: LoadBalancer
  selector:
    app: pokemon
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP