apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokemon
  template:
    metadata:
      labels:
        app: pokemon
    spec:
      containers:
      - name: pokemon
        image: zorranschool/pokemonweb
        env:
        - name: DB_HOST
          value: mysql.default.svc.cluster.local
        - name: DB_USER
          value: zorran
        - name: DB_PASS
          value: dbboi.!
        - name: DB_NAME
          value: pokemondb
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-service
spec:
  type: NodePort
  selector:
    app: pokemon
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001